name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - run: dotnet build --configuration Release

    - name: Upload test artifacts
      uses: actions/upload-artifact@v4
      with:
        name: test-artifacts
        path: artifacts/bin/RichardJM.Coverlet.Tests

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download test artifacts
      uses: actions/download-artifact@v4
      with:
        name: test-artifacts
        path: artifacts/bin/RichardJM.Coverlet.Tests

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - run: dotnet restore

    - run: dotnet test --configuration Release --no-build --collect:"XPlat Code Coverage" --results-directory artifacts/TestResults

    - name: Upload test results
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: artifacts/TestResults

    - name: Report code coverage
      uses: codecov/codecov-action@v5
      with:
        files: artifacts/TestResults/**/coverage.cobertura.xml
        fail_ci_if_error: true
